services:
  postgres:
    image: postgres:latest
    container_name: eximia_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: credito_consignado
      PGDATA: /var/lib/postgresql/data
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: eximia_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/pgadmin4/servers.json

  Redis:
    container_name: eximia_redis
    image: redis:7.4.1-alpine     
    command: redis-server --requirepass admin
    ports:
       - "6379:6379"
      
volumes:
  postgres_data:
  pgadmin_data: