// <auto-generated />
using System;
using Eximia.CreditoConsignado.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eximia.CreditoConsignado.ORM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eximia.CreditoConsignado.ORM.EntityTypes.CpfFraudeType", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.HasKey("Cpf");

                    b.ToTable("CpfFraude");
                });

            modelBuilder.Entity("Eximia.CreditoConsignado.ORM.EntityTypes.PropostaType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proposta");
                });
#pragma warning restore 612, 618
        }
    }
}
